class ProfitMenteAudioEngine{
 constructor(){this.ctx=null;this.master=null;this.monitor=null;this.recordDest=null;this.nodes=[];this.trackGains={};this.envelopes=typeof ProfitMenteAudioEnvelopeEngine!=='undefined'?new ProfitMenteAudioEnvelopeEngine():null;this.ducking=typeof ProfitMenteAudioDuckingEngine!=='undefined'?ProfitMenteAudioDuckingEngine:null}
 init(){if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.monitor=this.ctx.createGain();this.recordDest=this.ctx.createMediaStreamDestination();this.master.connect(this.monitor);this.monitor.connect(this.ctx.destination);this.master.connect(this.recordDest);for(const track of [4,5,6]){const gain=this.ctx.createGain();gain.gain.value=1;gain.connect(this.master);this.trackGains[track]=gain}}
 trackGainValue(project,track){const raw=project?.trackState?.[track]?.gain??project?.trackState?.[String(track)]?.gain,n=Number(raw);return Math.max(0,Math.min(2,Number.isFinite(n)?n:1))}
 syncTrackGains(project){this.init();for(const track of [4,5,6])this.trackGains[track].gain.value=this.trackGainValue(project,track)}
 setTrackGain(track,value){this.init();track=Number(track);if(!this.trackGains[track])return null;const n=Number(value),gain=Math.max(0,Math.min(2,Number.isFinite(n)?n:1));this.trackGains[track].gain.value=gain;return gain}
 visualTrackHidden(project,track){const s=project?.trackState?.[track]??project?.trackState?.[String(track)]??{};return !!(s&&typeof s==='object'&&s.hidden)}
 async buffer(blob){this.init();return await this.ctx.decodeAudioData(await blob.arrayBuffer())}
 musicGain(project,clip){return this.ducking?this.ducking.baseVolume(clip):(clip.volume??.22)}
 envelope(clip){if(this.envelopes)return this.envelopes.forClip(clip);const d=Math.max(.001,Number(clip.duration)||.001);let fadeIn=Math.max(0,Math.min(d,Number(clip.fadeIn??.18)||0)),fadeOut=Math.max(0,Math.min(d,Number(clip.fadeOut??.25)||0));if(fadeIn+fadeOut>d){const k=d/(fadeIn+fadeOut);fadeIn*=k;fadeOut*=k}return {fadeIn,fadeOut}}
 gainAt(clip,t){if(this.envelopes)return this.envelopes.gainAt(clip,t);const d=Math.max(.001,Number(clip.duration)||.001),e=this.envelope(clip);let g=1;if(e.fadeIn>0&&t<e.fadeIn)g=Math.min(g,t/e.fadeIn);if(e.fadeOut>0&&t>d-e.fadeOut)g=Math.min(g,(d-t)/e.fadeOut);return Math.max(0,Math.min(1,g))}
 scheduleEnvelope(clip,gain,volume,at,localStart,localEnd){const env=this.envelope(clip),clipDur=Math.max(.001,Number(clip.duration)||.001),startGain=volume*this.gainAt(clip,localStart);gain.gain.cancelScheduledValues(at);gain.gain.setValueAtTime(startGain,at);const fadeInEnd=env.fadeIn,fadeOutStart=clipDur-env.fadeOut;if(env.fadeIn>0&&localStart<fadeInEnd&&localEnd>localStart){const t=Math.min(localEnd,fadeInEnd);gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,t),at+(t-localStart))}if(localEnd>fadeOutStart&&env.fadeOut>0){const enter=Math.max(localStart,fadeOutStart);if(enter>localStart)gain.gain.setValueAtTime(volume*this.gainAt(clip,enter),at+(enter-localStart));gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,localEnd),at+(localEnd-localStart))}else if(localEnd>Math.max(localStart,fadeInEnd)){gain.gain.setValueAtTime(volume,at+(localEnd-localStart))}}
 scheduleDucking(project,clip,node,at,localStart,localEnd){
   node.gain.cancelScheduledValues(at);if(Number(clip.track)!==5||!this.ducking){node.gain.setValueAtTime(1,at);return}
   node.gain.setValueAtTime(this.ducking.multiplierAt(project,clip,localStart),at);
   for(const event of this.ducking.events(project,clip,localStart,localEnd))node.gain.setValueAtTime(event.value,at+(event.time-localStart));
 }
 async schedule(project,assets,from=0,monitor=true){this.stop();this.init();this.syncTrackGains(project);this.monitor.gain.value=monitor?1:0;await this.ctx.resume();const now=this.ctx.currentTime+.05;for(const clip of project.clips.filter(c=>[4,5,6].includes(c.track)&&c.asset&&c.start+c.duration>from)){const a=assets.find(x=>x.id===clip.asset);if(!a||a.type!=='audio')continue;try{const src=this.ctx.createBufferSource(),gain=this.ctx.createGain(),duck=this.ctx.createGain(),buf=await this.buffer(a.blob);src.buffer=buf;src.connect(gain);gain.connect(duck);duck.connect(this.trackGains[Number(clip.track)]||this.master);const speed=Math.max(.25,Math.min(4,Number(clip.speed)||1));src.playbackRate.value=speed;let volume=clip.track===5?this.musicGain(project,clip):(clip.volume??1),start=Math.max(clip.start,from),timelineOffset=Math.max(0,from-clip.start),sourceOffset=Math.max(0,Number(clip.sourceOffset)||0)+timelineOffset*speed,timelineDur=Math.min(clip.duration-timelineOffset,(buf.duration-sourceOffset)/speed),sourceDur=timelineDur*speed,at=now+(start-from);if(timelineDur<=0||sourceDur<=0)continue;const clipDur=Math.max(.001,Number(clip.duration)||.001),localStart=timelineOffset,localEnd=Math.min(clipDur,localStart+timelineDur);this.scheduleEnvelope(clip,gain,volume,at,localStart,localEnd);this.scheduleDucking(project,clip,duck,at,localStart,localEnd);src.start(at,sourceOffset,sourceDur);this.nodes.push(src)}catch(e){console.warn('Audio omitido',a.name,e)}}
   for(const clip of project.clips.filter(c=>[0,1].includes(Number(c.track))&&c.asset&&!c.muted&&!this.visualTrackHidden(project,Number(c.track))&&Number(c.start||0)+Number(c.duration||0)>from)){const a=assets.find(x=>x.id===clip.asset);if(!a||a.type!=='video')continue;try{const src=this.ctx.createBufferSource(),gain=this.ctx.createGain(),buf=await this.buffer(a.blob);src.buffer=buf;src.connect(gain);gain.connect(this.master);const speed=Math.max(.25,Math.min(4,Number(clip.speed)||1));src.playbackRate.value=speed;const volume=Math.max(0,Math.min(2,Number(clip.sourceVolume??1)||0)),start=Math.max(Number(clip.start)||0,from),timelineOffset=Math.max(0,from-(Number(clip.start)||0)),sourceOffset=Math.max(0,Number(clip.sourceOffset)||0)+timelineOffset*speed,timelineDur=Math.min((Number(clip.duration)||0)-timelineOffset,(buf.duration-sourceOffset)/speed),sourceDur=timelineDur*speed,at=now+(start-from);if(timelineDur<=0||sourceDur<=0)continue;const clipDur=Math.max(.001,Number(clip.duration)||.001),localStart=timelineOffset,localEnd=Math.min(clipDur,localStart+timelineDur);this.scheduleEnvelope(clip,gain,volume,at,localStart,localEnd);src.start(at,sourceOffset,sourceDur);this.nodes.push(src)}catch(e){console.warn('Audio original de video omitido',a.name,e)}}
 }
 stream(){this.init();return this.recordDest.stream}
 stop(){for(const n of this.nodes)try{n.stop()}catch{}this.nodes=[]}
 setMaster(v){this.init();this.master.gain.value=Math.max(0,Math.min(2,v))}
}
if(typeof window!=='undefined')window.ProfitMenteAudioEngine=ProfitMenteAudioEngine;
if(typeof module!=='undefined'&&module.exports)module.exports={ProfitMenteAudioEngine};