class ProfitMenteAudioEngine{
 constructor(){this.ctx=null;this.master=null;this.monitor=null;this.recordDest=null;this.nodes=[];this.trackGains={};this._scheduleSeq=0;this.envelopes=typeof ProfitMenteAudioEnvelopeEngine!=='undefined'?new ProfitMenteAudioEnvelopeEngine():null;this.ducking=typeof ProfitMenteAudioDuckingEngine!=='undefined'?ProfitMenteAudioDuckingEngine:null}
 init(){if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.monitor=this.ctx.createGain();this.recordDest=this.ctx.createMediaStreamDestination();this.master.connect(this.monitor);this.monitor.connect(this.ctx.destination);this.master.connect(this.recordDest);for(const track of [4,5,6]){const gain=this.ctx.createGain();gain.gain.value=1;gain.connect(this.master);this.trackGains[track]=gain}}
 finiteNumber(value){if(typeof value==='number')return Number.isFinite(value)?value:null;if(typeof value==='string'){const raw=value.trim();if(!raw)return null;const n=Number(raw);return Number.isFinite(n)?n:null}return null}
 strictFlag(value){return value===true}
 canonicalTrack(track){if(typeof track==='boolean'||track===null||track===undefined)return null;const raw=typeof track==='string'?track.trim():track;if(raw==='')return null;const n=Number(raw);return Number.isInteger(n)&&n>=0&&n<=6?(Object.is(n,-0)?0:n):null}
 trackStateValue(project,track){const canonical=this.canonicalTrack(track);if(canonical===null)return {};const merged={};const canonicalKey=String(canonical);for(const map of [project?.trackStates,project?.trackState]){if(!map||typeof map!=='object')continue;const aliases=Object.entries(map).filter(([key,value])=>this.canonicalTrack(key)===canonical&&value&&typeof value==='object'&&!Array.isArray(value));const protectedFlags=Object.fromEntries(['hidden','muted','solo'].map(flag=>[flag,this.strictFlag(merged[flag])||aliases.some(([,value])=>this.strictFlag(value[flag]))]));for(const [key,value] of aliases)if(key!==canonicalKey)Object.assign(merged,value);for(const [key,value] of aliases)if(key===canonicalKey)Object.assign(merged,value);for(const flag of ['hidden','muted','solo']){if(protectedFlags[flag])merged[flag]=true;else if(flag in merged&&!this.strictFlag(merged[flag]))merged[flag]=false}}return merged}
 canonicalMediaId(id){if(id===null||id===undefined||typeof id==='boolean')return null;if(typeof id==='string'){const s=id.trim();if(!s)return null;const n=Number(s);if(Number.isFinite(n))return String(Object.is(n,-0)?0:n);return s}if(typeof id==='number'&&Number.isFinite(id))return String(Object.is(id,-0)?0:id);return null}
 mediaAssigned(id){return this.canonicalMediaId(id)!==null}
 findAsset(assets,id){const key=this.canonicalMediaId(id);if(key===null)return null;return (assets||[]).find(a=>this.canonicalMediaId(a?.id)===key)||null}
 trackGainValue(project,track){const n=this.finiteNumber(this.trackStateValue(project,track)?.gain);return Math.max(0,Math.min(2,n===null?1:n))}
 syncTrackGains(project){this.init();for(const track of [4,5,6])this.trackGains[track].gain.value=this.trackGainValue(project,track)}
 setTrackGain(track,value){this.init();track=this.canonicalTrack(track);if(track===null||!this.trackGains[track])return null;const n=this.finiteNumber(value),gain=Math.max(0,Math.min(2,n===null?1:n));this.trackGains[track].gain.value=gain;return gain}
 visualTrackHidden(project,track){const canonical=this.canonicalTrack(track);if(canonical===null)return false;const s=this.trackStateValue(project,canonical),solo=[0,1,2,3].some(t=>this.strictFlag(this.trackStateValue(project,t).solo));return this.strictFlag(s.hidden)||(solo&&!this.strictFlag(s.solo))}
 audioTrackMuted(project,track){const canonical=this.canonicalTrack(track);if(canonical===null)return false;const s=this.trackStateValue(project,canonical),solo=[4,5,6].some(t=>this.strictFlag(this.trackStateValue(project,t).solo));return this.strictFlag(s.muted)||(solo&&!this.strictFlag(s.solo))}
 async buffer(blob){this.init();return await this.ctx.decodeAudioData(await blob.arrayBuffer())}
 musicGain(project,clip){return this.ducking?this.ducking.baseVolume(clip):(clip.volume??.22)}
 envelope(clip){if(this.envelopes)return this.envelopes.forClip(clip);const d=Math.max(.001,Number(clip.duration)||.001);let fadeIn=Math.max(0,Math.min(d,Number(clip.fadeIn??.18)||0)),fadeOut=Math.max(0,Math.min(d,Number(clip.fadeOut??.25)||0));if(fadeIn+fadeOut>d){const k=d/(fadeIn+fadeOut);fadeIn*=k;fadeOut*=k}return {fadeIn,fadeOut}}
 gainAt(clip,t){if(this.envelopes)return this.envelopes.gainAt(clip,t);const d=Math.max(.001,Number(clip.duration)||.001),e=this.envelope(clip);let g=1;if(e.fadeIn>0&&t<e.fadeIn)g=Math.min(g,t/e.fadeIn);if(e.fadeOut>0&&t>d-e.fadeOut)g=Math.min(g,(d-t)/e.fadeOut);return Math.max(0,Math.min(1,g))}
 scheduleEnvelope(clip,gain,volume,at,localStart,localEnd){const env=this.envelope(clip),clipDur=Math.max(.001,Number(clip.duration)||.001),startGain=volume*this.gainAt(clip,localStart);gain.gain.cancelScheduledValues(at);gain.gain.setValueAtTime(startGain,at);const fadeInEnd=env.fadeIn,fadeOutStart=clipDur-env.fadeOut;if(env.fadeIn>0&&localStart<fadeInEnd&&localEnd>localStart){const t=Math.min(localEnd,fadeInEnd);gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,t),at+(t-localStart))}if(localEnd>fadeOutStart&&env.fadeOut>0){const enter=Math.max(localStart,fadeOutStart);if(enter>localStart)gain.gain.setValueAtTime(volume*this.gainAt(clip,enter),at+(enter-localStart));gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,localEnd),at+(localEnd-localStart))}else if(localEnd>Math.max(localStart,fadeInEnd)){gain.gain.setValueAtTime(volume,at+(localEnd-localStart))}}
 scheduleDucking(project,clip,node,at,localStart,localEnd){node.gain.cancelScheduledValues(at);if(this.canonicalTrack(clip.track)!==5||!this.ducking){node.gain.setValueAtTime(1,at);return}node.gain.setValueAtTime(this.ducking.multiplierAt(project,clip,localStart),at);for(const event of this.ducking.events(project,clip,localStart,localEnd))node.gain.setValueAtTime(event.value,at+(event.time-localStart))}
 async schedule(project,assets,from=0,monitor=true){
   this.stop();const scheduleId=this._scheduleSeq;this.init();this.syncTrackGains(project);this.monitor.gain.value=monitor?1:0;await this.ctx.resume();
   const audioClips=(project?.clips||[]).filter(c=>[4,5,6].includes(this.canonicalTrack(c.track))&&this.mediaAssigned(c.asset)&&!this.strictFlag(c.muted)&&!this.audioTrackMuted(project,c.track)&&Number(c.start||0)+Number(c.duration||0)>from);
   const videoClips=(project?.clips||[]).filter(c=>[0,1].includes(this.canonicalTrack(c.track))&&this.mediaAssigned(c.asset)&&!this.strictFlag(c.muted)&&!this.visualTrackHidden(project,c.track)&&Number(c.start||0)+Number(c.duration||0)>from);
   const decoded=new Map(),requested=new Map();
   for(const [clip,expectedType] of [...audioClips.map(c=>[c,'audio']),...videoClips.map(c=>[c,'video'])]){
     const a=this.findAsset(assets,clip.asset),key=this.canonicalMediaId(a?.id);if(!a||a.type!==expectedType||key===null||requested.has(key))continue;
     requested.set(key,{a,expectedType});
   }
   await Promise.all([...requested.entries()].map(async([key,{a,expectedType}])=>{
     try{const buf=await this.buffer(a.blob);if(scheduleId===this._scheduleSeq)decoded.set(key,buf)}catch(e){console.warn(expectedType==='audio'?'Audio omitido':'Audio original de video omitido',a.name,e)}
   }));
   if(scheduleId!==this._scheduleSeq)return false;
   const now=this.ctx.currentTime+.05;
   for(const clip of audioClips){const a=this.findAsset(assets,clip.asset),buf=decoded.get(this.canonicalMediaId(a?.id));if(!a||a.type!=='audio'||!buf)continue;try{const src=this.ctx.createBufferSource(),gain=this.ctx.createGain(),duck=this.ctx.createGain();src.buffer=buf;src.connect(gain);gain.connect(duck);duck.connect(this.trackGains[this.canonicalTrack(clip.track)]||this.master);const speed=Math.max(.25,Math.min(4,Number(clip.speed)||1));src.playbackRate.value=speed;let volume=this.canonicalTrack(clip.track)===5?this.musicGain(project,clip):(clip.volume??1),clipStart=Number(clip.start)||0,clipDuration=Number(clip.duration)||0,start=Math.max(clipStart,from),timelineOffset=Math.max(0,from-clipStart),sourceOffset=Math.max(0,Number(clip.sourceOffset)||0)+timelineOffset*speed,timelineDur=Math.min(clipDuration-timelineOffset,(buf.duration-sourceOffset)/speed),sourceDur=timelineDur*speed,at=now+(start-from);if(timelineDur<=0||sourceDur<=0)continue;const clipDur=Math.max(.001,clipDuration||.001),localStart=timelineOffset,localEnd=Math.min(clipDur,localStart+timelineDur);this.scheduleEnvelope(clip,gain,volume,at,localStart,localEnd);this.scheduleDucking(project,clip,duck,at,localStart,localEnd);src.start(at,sourceOffset,sourceDur);this.nodes.push(src)}catch(e){console.warn('Audio omitido',a.name,e)}}
   for(const clip of videoClips){const a=this.findAsset(assets,clip.asset),buf=decoded.get(this.canonicalMediaId(a?.id));if(!a||a.type!=='video'||!buf)continue;try{const src=this.ctx.createBufferSource(),gain=this.ctx.createGain();src.buffer=buf;src.connect(gain);gain.connect(this.master);const speed=Math.max(.25,Math.min(4,Number(clip.speed)||1));src.playbackRate.value=speed;const volume=Math.max(0,Math.min(2,Number(clip.sourceVolume??1)||0)),clipStart=Number(clip.start)||0,clipDuration=Number(clip.duration)||0,start=Math.max(clipStart,from),timelineOffset=Math.max(0,from-clipStart),sourceOffset=Math.max(0,Number(clip.sourceOffset)||0)+timelineOffset*speed,timelineDur=Math.min(clipDuration-timelineOffset,(buf.duration-sourceOffset)/speed),sourceDur=timelineDur*speed,at=now+(start-from);if(timelineDur<=0||sourceDur<=0)continue;const clipDur=Math.max(.001,clipDuration||.001),localStart=timelineOffset,localEnd=Math.min(clipDur,localStart+timelineDur);this.scheduleEnvelope(clip,gain,volume,at,localStart,localEnd);src.start(at,sourceOffset,sourceDur);this.nodes.push(src)}catch(e){console.warn('Audio original de video omitido',a.name,e)}}
   return scheduleId===this._scheduleSeq;
 }
 stream(){this.init();return this.recordDest.stream}
 stop(){this._scheduleSeq++;for(const n of this.nodes)try{n.stop()}catch{}this.nodes=[]}
 setMaster(v){this.init();this.master.gain.value=Math.max(0,Math.min(2,v))}
}
if(typeof window!=='undefined')window.ProfitMenteAudioEngine=ProfitMenteAudioEngine;
if(typeof module!=='undefined'&&module.exports)module.exports={ProfitMenteAudioEngine};
