class ProfitMenteAudioEngine{
 constructor(){this.ctx=null;this.master=null;this.monitor=null;this.recordDest=null;this.nodes=[];this.envelopes=typeof ProfitMenteAudioEnvelopeEngine!=='undefined'?new ProfitMenteAudioEnvelopeEngine():null}
 init(){if(this.ctx)return;this.ctx=new (window.AudioContext||window.webkitAudioContext)();this.master=this.ctx.createGain();this.monitor=this.ctx.createGain();this.recordDest=this.ctx.createMediaStreamDestination();this.master.connect(this.monitor);this.monitor.connect(this.ctx.destination);this.master.connect(this.recordDest)}
 async buffer(blob){this.init();return await this.ctx.decodeAudioData(await blob.arrayBuffer())}
 musicGain(project,clip){const voice=project.clips.some(v=>v.track===6&&v.start<clip.start+clip.duration&&v.start+v.duration>clip.start);return clip.volume??(voice?.16:.25)}
 envelope(clip){if(this.envelopes)return this.envelopes.forClip(clip);const d=Math.max(.001,Number(clip.duration)||.001);let fadeIn=Math.max(0,Math.min(d,Number(clip.fadeIn??.18)||0)),fadeOut=Math.max(0,Math.min(d,Number(clip.fadeOut??.25)||0));if(fadeIn+fadeOut>d){const k=d/(fadeIn+fadeOut);fadeIn*=k;fadeOut*=k}return {fadeIn,fadeOut}}
 gainAt(clip,t){if(this.envelopes)return this.envelopes.gainAt(clip,t);const d=Math.max(.001,Number(clip.duration)||.001),e=this.envelope(clip);let g=1;if(e.fadeIn>0&&t<e.fadeIn)g=Math.min(g,t/e.fadeIn);if(e.fadeOut>0&&t>d-e.fadeOut)g=Math.min(g,(d-t)/e.fadeOut);return Math.max(0,Math.min(1,g))}
 async schedule(project,assets,from=0,monitor=true){this.stop();this.init();this.monitor.gain.value=monitor?1:0;await this.ctx.resume();const now=this.ctx.currentTime+.05;for(const clip of project.clips.filter(c=>[4,5,6].includes(c.track)&&c.asset&&c.start+c.duration>from)){const a=assets.find(x=>x.id===clip.asset);if(!a||a.type!=='audio')continue;try{const src=this.ctx.createBufferSource(),gain=this.ctx.createGain(),buf=await this.buffer(a.blob);src.buffer=buf;src.connect(gain);gain.connect(this.master);const speed=Math.max(.25,Math.min(4,Number(clip.speed)||1));src.playbackRate.value=speed;let volume=clip.track===5?this.musicGain(project,clip):(clip.volume??1),start=Math.max(clip.start,from),timelineOffset=Math.max(0,from-clip.start),sourceOffset=Math.max(0,Number(clip.sourceOffset)||0)+timelineOffset*speed,timelineDur=Math.min(clip.duration-timelineOffset,(buf.duration-sourceOffset)/speed),sourceDur=timelineDur*speed,at=now+(start-from);if(timelineDur<=0||sourceDur<=0)continue;const env=this.envelope(clip),clipDur=Math.max(.001,Number(clip.duration)||.001),localStart=timelineOffset,localEnd=Math.min(clipDur,localStart+timelineDur),startGain=volume*this.gainAt(clip,localStart);gain.gain.cancelScheduledValues(at);gain.gain.setValueAtTime(startGain,at);const fadeInEnd=env.fadeIn,fadeOutStart=clipDur-env.fadeOut;if(env.fadeIn>0&&localStart<fadeInEnd&&localEnd>localStart){const t=Math.min(localEnd,fadeInEnd);gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,t),at+(t-localStart))}if(localEnd>fadeOutStart&&env.fadeOut>0){const enter=Math.max(localStart,fadeOutStart);if(enter>localStart)gain.gain.setValueAtTime(volume*this.gainAt(clip,enter),at+(enter-localStart));gain.gain.linearRampToValueAtTime(volume*this.gainAt(clip,localEnd),at+(localEnd-localStart))}else if(localEnd>Math.max(localStart,fadeInEnd)){gain.gain.setValueAtTime(volume,at+(localEnd-localStart))}src.start(at,sourceOffset,sourceDur);this.nodes.push(src)}catch(e){console.warn('Audio omitido',a.name,e)}}}
 stream(){this.init();return this.recordDest.stream}
 stop(){for(const n of this.nodes)try{n.stop()}catch{}this.nodes=[]}
 setMaster(v){this.init();this.master.gain.value=Math.max(0,Math.min(2,v))}
}
window.ProfitMenteAudioEngine=ProfitMenteAudioEngine;