class ProfitMenteMarkerEngine{
  constructor(opts={}){this.getProject=opts.getProject;this.persist=opts.persist;this.getTime=opts.getTime;this.setTime=opts.setTime;this.container=opts.container;this.getFrameRate=opts.getFrameRate;}
  number(v,fallback=null){if(typeof v==='number')return Number.isFinite(v)?v:fallback;if(typeof v!=='string'||!v.trim())return fallback;const n=Number(v);return Number.isFinite(n)?n:fallback;}
  scalar(v){if(typeof v==='number')return Number.isFinite(v)?String(v):null;if(typeof v!=='string')return null;const s=v.trim();return s||null;}
  idKey(v){const s=this.scalar(v);if(s===null)return null;if(/^[+-]?(?:\d+\.?\d*|\.\d+)$/.test(s)){const n=Number(s);if(Number.isFinite(n))return `n:${Object.is(n,-0)?0:n}`;}return `s:${s}`;}
  duration(){return Math.max(0,this.number(this.getProject?.()?.duration,0));}
  frameRate(){const p=this.getProject?.()||{},raw=this.getFrameRate?.()??p.frameRate??p.fps??30,n=this.number(raw,30);return n>0&&n<=240?n:30;}
  snapTime(value){const raw=this.number(value,null);if(raw===null)return null;const fps=this.frameRate(),t=Math.round(Math.max(0,Math.min(this.duration(),raw))*fps)/fps;return Math.max(0,Math.min(this.duration(),t));}
  newId(){return globalThis.crypto?.randomUUID?.()||`m-${Date.now()}-${Math.random().toString(36).slice(2)}`;}
  normalizeMarker(marker,index=0){if(!marker||typeof marker!=='object'||Array.isArray(marker))return null;const t=this.snapTime(marker.time);if(t===null)return null;const rawId=this.scalar(marker.id),id=rawId||`legacy-marker-${index}-${Math.round(t*this.frameRate())}`;const label=typeof marker.label==='string'&&marker.label.trim()?marker.label.trim().slice(0,80):'Marcador';const kind=['note','chapter','cue'].includes(marker.kind)?marker.kind:'note';return {id,time:t,label,kind};}
  markers(){const p=this.getProject?.();if(!p||typeof p!=='object'||Array.isArray(p))return [];if(!Array.isArray(p.markers)){p.markers=[];return p.markers;}const seen=new Set();p.markers=p.markers.map((m,i)=>this.normalizeMarker(m,i)).filter(Boolean).map(m=>{let key=this.idKey(m.id);if(key===null||seen.has(key)){m={...m,id:this.newId()};key=this.idKey(m.id);}seen.add(key);return m;}).sort((a,b)=>a.time-b.time);return p.markers;}
  transaction(change){const p=this.getProject?.();if(!p||typeof p!=='object'||Array.isArray(p))return null;const before=Array.isArray(p.markers)?p.markers.map(m=>m&&typeof m==='object'&&!Array.isArray(m)?{...m}:m):p.markers;try{const result=change(p);if(result===false||result===null)return result;this.persist?.();this.render();return result;}catch(error){p.markers=before;try{this.render();}catch{}throw error;}}
  add(time,label='Marcador',kind='note'){const t=this.snapTime(time);if(t===null)return null;const safeLabel=typeof label==='string'&&label.trim()?label.trim().slice(0,80):'Marcador',safeKind=['note','chapter','cue'].includes(kind)?kind:'note';return this.transaction(p=>{const list=this.markers(),m={id:this.newId(),time:t,label:safeLabel,kind:safeKind};list.push(m);p.markers=list.sort((a,b)=>a.time-b.time);return m;});}
  find(id){const key=this.idKey(id);if(key===null)return null;return this.markers().find(m=>this.idKey(m.id)===key)||null;}
  remove(id){const key=this.idKey(id);if(key===null)return false;return !!this.transaction(p=>{const list=this.markers(),next=list.filter(m=>this.idKey(m.id)!==key);if(next.length===list.length)return false;p.markers=next;return true;});}
  rename(id,label){const key=this.idKey(id);if(key===null||typeof label!=='string')return false;return !!this.transaction(()=>{const m=this.find(id);if(!m)return false;m.label=(label.trim()||'Marcador').slice(0,80);return true;});}
  move(id,time){const key=this.idKey(id),t=this.snapTime(time);if(key===null||t===null)return false;return !!this.transaction(p=>{const m=this.find(id);if(!m)return false;m.time=t;p.markers=this.markers().sort((a,b)=>a.time-b.time);return true;});}
  setKind(id,kind){if(!['note','chapter','cue'].includes(kind)||this.idKey(id)===null)return false;return !!this.transaction(()=>{const m=this.find(id);if(!m)return false;m.kind=kind;return true;});}
  next(dir=1){const current=this.number(this.getTime?.(),0),list=this.markers().slice().sort((a,b)=>a.time-b.time);if(!list.length)return null;const forward=this.number(dir,1)>0;let m=forward?list.find(x=>x.time>current+.001):list.slice().reverse().find(x=>x.time<current-.001);m=m||(forward?list[0]:list[list.length-1]);this.setTime?.(m.time);return m;}
  render(){if(!this.container||typeof document==='undefined')return;const duration=Math.max(.001,this.duration()||1);let lane=this.container.querySelector('.markerLane');if(!lane){lane=document.createElement('div');lane.className='markerLane';lane.title='Doble clic para añadir marcador · arrastra para mover';this.container.prepend(lane);lane.ondblclick=e=>{if(e.target!==lane)return;const r=lane.getBoundingClientRect();if(!r.width)return;this.add((e.clientX-r.left)/r.width*duration,'Marcador');};}
    lane.innerHTML=this.markers().map(m=>`<button class="timelineMarker marker-${m.kind}" data-marker="${this.escape(m.id)}" style="left:${Math.max(0,Math.min(100,m.time/duration*100))}%" title="${this.escape(m.label)} · ${m.time.toFixed(2)}s · ${m.kind}">◆<span>${this.escape(m.label)}</span></button>`).join('');
    lane.querySelectorAll('.timelineMarker').forEach(b=>{let dragState=null;b.onpointerdown=e=>{if(e.button!==0)return;const r=lane.getBoundingClientRect();if(!r.width)return;dragState={startX:e.clientX,rect:r,moved:false};b.setPointerCapture?.(e.pointerId);};b.onpointermove=e=>{if(!dragState)return;if(Math.abs(e.clientX-dragState.startX)>3)dragState.moved=true;if(!dragState.moved)return;const t=this.snapTime((e.clientX-dragState.rect.left)/dragState.rect.width*duration);if(t===null)return;b.style.left=`${Math.max(0,Math.min(100,t/duration*100))}%`;};b.onpointerup=e=>{if(!dragState)return;const state=dragState;dragState=null;if(!state.moved)return;const t=this.snapTime((e.clientX-state.rect.left)/state.rect.width*duration);b.dataset.dragged='1';if(t!==null)this.move(b.dataset.marker,t);};b.onclick=e=>{e.stopPropagation();if(b.dataset.dragged){delete b.dataset.dragged;return;}const m=this.find(b.dataset.marker);if(m)this.setTime?.(m.time);};b.ondblclick=e=>{e.stopPropagation();const m=this.find(b.dataset.marker);if(!m)return;const label=prompt('Nombre del marcador',m.label);if(label!==null)this.rename(m.id,label);};b.oncontextmenu=e=>{e.preventDefault();if(confirm('¿Eliminar este marcador?'))this.remove(b.dataset.marker);};});}
  escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
}
window.ProfitMenteMarkerEngine=ProfitMenteMarkerEngine;
