class ProfitMenteMarkerEngine{
  constructor(opts={}){this.getProject=opts.getProject;this.persist=opts.persist;this.getTime=opts.getTime;this.setTime=opts.setTime;this.container=opts.container;}
  number(v,fallback=null){if(typeof v==='number')return Number.isFinite(v)?v:fallback;if(typeof v!=='string'||!v.trim())return fallback;const n=Number(v);return Number.isFinite(n)?n:fallback;}
  duration(){return Math.max(0,this.number(this.getProject()?.duration,0));}
  normalizeMarker(marker,index=0){if(!marker||typeof marker!=='object'||Array.isArray(marker))return null;const t=this.number(marker.time,null);if(t===null)return null;const id=(typeof marker.id==='string'&&marker.id.trim())?marker.id.trim():`legacy-marker-${index}-${Math.max(0,t)}`;const label=String(marker.label||'Marcador').slice(0,80);return {id,time:Math.max(0,Math.min(this.duration(),t)),label};}
  markers(){const p=this.getProject();if(!Array.isArray(p.markers)){p.markers=[];return p.markers;}p.markers=p.markers.map((m,i)=>this.normalizeMarker(m,i)).filter(Boolean);return p.markers;}
  add(time,label='Marcador'){const p=this.getProject(),raw=this.number(time,null);if(raw===null)return null;const t=Math.max(0,Math.min(this.duration(),raw));const m={id:(globalThis.crypto?.randomUUID?.()||`m-${Date.now()}-${Math.random()}`),time:t,label:String(label||'Marcador').slice(0,80)};this.markers().push(m);p.markers.sort((a,b)=>a.time-b.time);this.persist();this.render();return m;}
  remove(id){if(typeof id!=='string'||!id)return false;const p=this.getProject(),before=this.markers().length;p.markers=p.markers.filter(m=>m.id!==id);if(p.markers.length===before)return false;this.persist();this.render();return true;}
  rename(id,label){if(typeof id!=='string'||!id)return false;const m=this.markers().find(x=>x.id===id);if(!m)return false;m.label=String(label||'Marcador').slice(0,80);this.persist();this.render();return true;}
  next(dir=1){const current=this.number(this.getTime?.(),0),list=this.markers().slice().sort((a,b)=>a.time-b.time);if(!list.length)return null;const forward=this.number(dir,1)>0;let m=forward?list.find(x=>x.time>current+.001):list.slice().reverse().find(x=>x.time<current-.001);m=m||(forward?list[0]:list[list.length-1]);this.setTime(m.time);return m;}
  render(){if(!this.container)return;const duration=Math.max(.001,this.duration()||1);let lane=this.container.querySelector('.markerLane');if(!lane){lane=document.createElement('div');lane.className='markerLane';lane.title='Doble clic para añadir marcador';this.container.prepend(lane);lane.ondblclick=e=>{if(e.target!==lane)return;const r=lane.getBoundingClientRect();if(!r.width)return;this.add((e.clientX-r.left)/r.width*duration,'Marcador')}}lane.innerHTML=this.markers().map(m=>`<button class="timelineMarker" data-marker="${this.escape(m.id)}" style="left:${Math.max(0,Math.min(100,m.time/duration*100))}%" title="${this.escape(m.label)} · ${m.time.toFixed(2)}s">◆<span>${this.escape(m.label)}</span></button>`).join('');lane.querySelectorAll('.timelineMarker').forEach(b=>{b.onclick=e=>{e.stopPropagation();const m=this.markers().find(x=>x.id===b.dataset.marker);if(m)this.setTime(m.time)};b.ondblclick=e=>{e.stopPropagation();const m=this.markers().find(x=>x.id===b.dataset.marker);if(!m)return;const label=prompt('Nombre del marcador',m.label);if(label!==null)this.rename(m.id,label)};b.oncontextmenu=e=>{e.preventDefault();if(confirm('¿Eliminar este marcador?'))this.remove(b.dataset.marker)}})}
  escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
}
window.ProfitMenteMarkerEngine=ProfitMenteMarkerEngine;
