class ProfitMenteMarkerEngine{
  constructor(opts={}){this.getProject=opts.getProject;this.persist=opts.persist;this.getTime=opts.getTime;this.setTime=opts.setTime;this.container=opts.container;}
  markers(){const p=this.getProject();if(!Array.isArray(p.markers))p.markers=[];return p.markers;}
  add(time,label='Marcador'){const p=this.getProject(),t=Math.max(0,Math.min(+p.duration||0,+time||0));const m={id:(globalThis.crypto?.randomUUID?.()||`m-${Date.now()}-${Math.random()}`),time:t,label:String(label||'Marcador').slice(0,80)};this.markers().push(m);p.markers.sort((a,b)=>a.time-b.time);this.persist();this.render();return m;}
  remove(id){const p=this.getProject();p.markers=this.markers().filter(m=>m.id!==id);this.persist();this.render();}
  rename(id,label){const m=this.markers().find(x=>x.id===id);if(!m)return;m.label=String(label||'Marcador').slice(0,80);this.persist();this.render();}
  next(dir=1){const t=this.getTime(),list=this.markers().slice().sort((a,b)=>a.time-b.time);if(!list.length)return null;let m=dir>0?list.find(x=>x.time>t+.001):list.slice().reverse().find(x=>x.time<t-.001);m=m||(dir>0?list[0]:list[list.length-1]);this.setTime(m.time);return m;}
  render(){if(!this.container)return;const p=this.getProject(),duration=Math.max(.001,+p.duration||1);let lane=this.container.querySelector('.markerLane');if(!lane){lane=document.createElement('div');lane.className='markerLane';lane.title='Doble clic para añadir marcador';this.container.prepend(lane);lane.ondblclick=e=>{if(e.target!==lane)return;const r=lane.getBoundingClientRect();this.add((e.clientX-r.left)/r.width*duration,'Marcador')}}lane.innerHTML=this.markers().map(m=>`<button class="timelineMarker" data-marker="${m.id}" style="left:${Math.max(0,Math.min(100,m.time/duration*100))}%" title="${this.escape(m.label)} · ${m.time.toFixed(2)}s">◆<span>${this.escape(m.label)}</span></button>`).join('');lane.querySelectorAll('.timelineMarker').forEach(b=>{b.onclick=e=>{e.stopPropagation();const m=this.markers().find(x=>x.id===b.dataset.marker);if(m)this.setTime(m.time)};b.ondblclick=e=>{e.stopPropagation();const m=this.markers().find(x=>x.id===b.dataset.marker);if(!m)return;const label=prompt('Nombre del marcador',m.label);if(label!==null)this.rename(m.id,label)};b.oncontextmenu=e=>{e.preventDefault();if(confirm('¿Eliminar este marcador?'))this.remove(b.dataset.marker)}})}
  escape(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
}
window.ProfitMenteMarkerEngine=ProfitMenteMarkerEngine;
