class ProfitMenteQAEngine{
  inspect(project,assets){
    assets=Array.isArray(assets)?assets:[];
    const strictNumber=value=>{if(typeof value==='number')return Number.isFinite(value)?value:null;if(typeof value!=='string')return null;const text=value.trim();if(!text||!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?$/.test(text))return null;const number=Number(text);return Number.isFinite(number)?number:null};
    const trackKey=value=>{const number=strictNumber(value);return number!==null&&Number.isSafeInteger(number)&&number>=0&&number<=6?number:null};
    const mediaIdKey=value=>{if(typeof value==='string'){const key=value.trim();return key||null}if(typeof value==='number'&&Number.isSafeInteger(value))return String(value);return null};
    const issues=[],warnings=[]; const ids=new Set(assets.map(a=>mediaIdKey(a?.id)).filter(id=>id!==null));
    const projectDuration=strictNumber(project?.duration);
    if(projectDuration===null||projectDuration<=0)issues.push('Duración del proyecto inválida.');
    const timelineDuration=projectDuration!==null&&projectDuration>0?projectDuration:0;
    const VISUAL_TRACKS=[0,1,2,3],AUDIO_TRACKS=[4,5,6];
    const state=track=>{const target=trackKey(track);if(target===null)return {hidden:false,muted:false,locked:false,solo:false};const read=states=>{if(!states||typeof states!=='object')return {};const merged={hidden:false,muted:false,locked:false,solo:false};for(const [key,value] of Object.entries(states)){if(!value||typeof value!=='object')continue;const numeric=trackKey(key);if(numeric===target){merged.hidden=merged.hidden||value.hidden===true;merged.muted=merged.muted||value.muted===true;merged.locked=merged.locked||value.locked===true;merged.solo=merged.solo||value.solo===true}}return merged};const modern=read(project.trackState),legacy=read(project.trackStates);return {hidden:modern.hidden===true||legacy.hidden===true,muted:modern.muted===true||legacy.muted===true,locked:modern.locked===true||legacy.locked===true,solo:modern.solo===true||legacy.solo===true}};
    const soloSet=tracks=>{const set=new Set(tracks.filter(track=>state(track).solo));return set.size?set:null};
    const visualSolo=soloSet(VISUAL_TRACKS),audioSolo=soloSet(AUDIO_TRACKS);
    const activeTrack=value=>{const track=trackKey(value);if(track===null)return false;const s=state(track);if(VISUAL_TRACKS.includes(track))return !s.hidden&&(!visualSolo||visualSolo.has(track));if(AUDIO_TRACKS.includes(track))return !s.muted&&(!audioSolo||audioSolo.has(track));return false};
    const disabled=c=>!activeTrack(c?.track),assetKind=a=>a?.type==='video'||a?.type==='image'?'visual':a?.type==='audio'?'audio':'other',expectedKind=value=>{const track=trackKey(value);return [0,1].includes(track)?'visual':[4,5,6].includes(track)?'audio':'none'};
    const requireBlob=typeof document!=='undefined',usableBlob=a=>{if(!requireBlob&&a?.blob==null)return true;return !!a?.blob&&typeof a.blob.arrayBuffer==='function'&&(a.blob.size==null||Number(a.blob.size)>0)};
    if(!project.clips?.length)issues.push('El timeline está vacío.');
    const checkKeyframe=(c,k,label)=>{if(!k||typeof k!=='object'){issues.push(`Keyframe ${label} inválido: ${c.name||c.id}`);return}const ranges={positionX:[-100,100],positionY:[-100,100],scale:[.25,3],rotation:[-180,180],opacity:[0,1]};for(const [field,[lo,hi]] of Object.entries(ranges)){const v=Number(k[field]);if(!Number.isFinite(v)||v<lo||v>hi)issues.push(`Keyframe ${label} ${field} fuera de rango: ${c.name||c.id}`)}};
    const checkColor=c=>{const ranges={brightness:[-100,100],contrast:[-90,100],saturation:[-100,200],hue:[-180,180]};for(const [field,[lo,hi]] of Object.entries(ranges)){if(c[field]==null)continue;const v=Number(c[field]);if(!Number.isFinite(v)||v<lo||v>hi)issues.push(`${field} fuera de rango: ${c.name||c.id}`)}if(Math.abs(Number(c.brightness)||0)>65)warnings.push(`Brillo extremo puede perder detalle: ${c.name||c.id}`);if((Number(c.saturation)||0)>150)warnings.push(`Saturación extrema puede producir colores artificiales: ${c.name||c.id}`)};
    const checkEnvelope=c=>{const d=Math.max(.001,Number(c.duration)||.001),fi=c.fadeIn==null?.18:Number(c.fadeIn),fo=c.fadeOut==null?.25:Number(c.fadeOut);if(!Number.isFinite(fi)||fi<0||fi>d+.001)issues.push(`Fade de entrada fuera de rango: ${c.name||c.id}`);if(!Number.isFinite(fo)||fo<0||fo>d+.001)issues.push(`Fade de salida fuera de rango: ${c.name||c.id}`);if(Number.isFinite(fi)&&Number.isFinite(fo)&&fi+fo>d+.001)warnings.push(`Fades de audio se solapan y serán normalizados: ${c.name||c.id}`)};
    const checkWordTimings=c=>{if(c.wordTimings==null)return;if(!Array.isArray(c.wordTimings)){issues.push(`Tiempos de palabras inválidos: ${c.name||c.id}`);return}const start=Number(c.start)||0,end=start+(Number(c.duration)||0);let previous=start-.001;for(const w of c.wordTimings){const ws=Number(w?.start),we=Number(w?.end),word=String(w?.word||'').trim();if(!word)issues.push(`Caption con palabra vacía: ${c.name||c.id}`);if(!Number.isFinite(ws)||!Number.isFinite(we)||we<=ws){issues.push(`Tiempo de palabra inválido: ${c.name||c.id}`);continue}if(ws<start-.03||we>end+.03)issues.push(`Palabra fuera del rango del caption: ${c.name||c.id}`);if(ws<previous-.01)issues.push(`Palabras desordenadas o solapadas: ${c.name||c.id}`);previous=we}if(c.animation==='word-by-word'&&!c.wordTimings.length)warnings.push(`Caption word-by-word sin palabras sincronizadas: ${c.name||c.id}`)};
    const checkMotionText=c=>{const name=String(c.name||'').trim();if(!name)issues.push(`Texto Motion vacío: ${c.id}`);if(name.length>180)warnings.push(`Texto Motion demasiado largo: ${name.slice(0,32)}…`);if(!['title','label','callout'].includes(c.textStyle||'title'))issues.push(`Estilo Motion inválido: ${name||c.id}`);if(!['none','fade','pop','slide-up'].includes(c.textAnimation||'pop'))issues.push(`Animación Motion inválida: ${name||c.id}`);for(const [field,lo,hi] of [['textX',-45,45],['textY',-45,45],['fontSize',16,84],['boxOpacity',0,1]]){const fallback=field==='textY'?-28:field==='fontSize'?40:field==='boxOpacity'?.55:0,v=Number(c[field]??fallback);if(!Number.isFinite(v)||v<lo||v>hi)issues.push(`${field} fuera de rango en Motion: ${name||c.id}`)}const color=/^#[0-9a-f]{6}$/i;if(c.textColor!=null&&!color.test(String(c.textColor)))issues.push(`Color de texto Motion inválido: ${name||c.id}`);if(c.boxColor!=null&&!color.test(String(c.boxColor)))issues.push(`Color de fondo Motion inválido: ${name||c.id}`)};
    for(const c of project.clips||[]){
      const track=trackKey(c?.track),inactive=disabled(c),assetId=mediaIdKey(c?.asset),start=strictNumber(c?.start),duration=strictNumber(c?.duration);
      if(track===null)issues.push(`Pista inválida: ${c.name||c.id}`);if(start===null||duration===null||start<0||duration<=0||start+duration>timelineDuration+.01)issues.push(`Clip fuera de rango: ${c.name||c.id}`);
      if(!inactive&&[0,1,4,5,6].includes(track)&&c?.asset!=null&&assetId===null)issues.push(`Identidad de medio inválida: ${c.name||c.id}`);
      const a=!inactive&&assetId!==null?assets.find(x=>mediaIdKey(x?.id)===assetId):null;if(!inactive&&assetId!==null&&!ids.has(assetId))issues.push(`Medio faltante: ${c.name||c.id}`);
      if(a){const expected=expectedKind(track),actual=assetKind(a);if(expected!=='none'&&actual!==expected)issues.push(`Tipo de medio incompatible con la pista: ${c.name||a.name}`);if(expected!=='none'&&!usableBlob(a))issues.push(`Archivo de medio vacío o no disponible: ${c.name||a.name}`);if(expected!=='none'&&a.mediaReadable===false)issues.push(`Medio no decodificable: ${c.name||a.name}${a.mediaError?' · '+a.mediaError:''}`)}
      if(!inactive&&[0,1].includes(track)&&c.fitMode!=null&&!['cover','contain'].includes(c.fitMode))issues.push(`Encuadre inválido: ${c.name||c.id}`);if(!inactive&&[0,1].includes(track))checkColor(c);if(!inactive&&c.keyframes!=null){if(!c.keyframes.start||!c.keyframes.end)issues.push(`Keyframes incompletos: ${c.name||c.id}`);else{checkKeyframe(c,c.keyframes.start,'inicio');checkKeyframe(c,c.keyframes.end,'fin')}}if(!inactive&&track===2)checkMotionText(c);if(!inactive&&track===3)checkWordTimings(c);
      const rawOffset=c?.sourceOffset==null?0:strictNumber(c.sourceOffset),rawSpeed=c?.speed==null?1:strictNumber(c.speed);if(rawOffset===null||rawOffset<0)issues.push(`Punto de entrada inválido: ${c.name||c.id}`);if(rawSpeed===null||rawSpeed<.25||rawSpeed>4)issues.push(`Velocidad de reproducción inválida: ${c.name||c.id}`);const sourceOffset=rawOffset!==null&&rawOffset>=0?rawOffset:0,speed=rawSpeed!==null&&rawSpeed>=.25&&rawSpeed<=4?rawSpeed:1;
      if(a&&([4,5,6].includes(track)||([0,1].includes(track)&&a.type==='video')))checkEnvelope(c);if(a?.duration&&['video','audio'].includes(a.type)){const sourceNeeded=Math.max(0,duration||0)*speed;if(sourceOffset>a.duration+.01)issues.push(`Punto de entrada fuera del archivo fuente: ${c.name||a.name}`);else if(sourceOffset+sourceNeeded>a.duration+.15)warnings.push(`Recorte supera el final del archivo fuente: ${c.name||a.name} · requiere ${(sourceOffset+sourceNeeded).toFixed(2)}s de ${Number(a.duration).toFixed(2)}s`)}
    }
    const visuals=(project.clips||[]).filter(c=>[0,1].includes(trackKey(c?.track))&&mediaIdKey(c?.asset)!==null&&activeTrack(c?.track));if(!visuals.length)warnings.push('No hay video o imagen visible asignado a las pistas visuales.');const colorGraded=visuals.filter(c=>['brightness','contrast','saturation','hue'].some(k=>Math.abs(Number(c[k])||0)>.001));const motion=(project.clips||[]).filter(c=>trackKey(c?.track)===2&&c.name&&activeTrack(c?.track));const audio=(project.clips||[]).filter(c=>[4,5,6].includes(trackKey(c?.track))&&mediaIdKey(c?.asset)!==null&&c.muted!==true&&activeTrack(c?.track));if(!audio.length)warnings.push('No hay voz, música ni SFX activos.');const captions=(project.clips||[]).filter(c=>trackKey(c?.track)===3&&c.name&&activeTrack(c?.track));if(!captions.length)warnings.push('No hay subtítulos/captions visibles.');
    const disabledTracks=[];for(let i=0;i<=6;i++)if(!activeTrack(i))disabledTracks.push(i);if(disabledTracks.length)warnings.push(`Pistas desactivadas para exportación: ${disabledTracks.join(', ')}`);
    const usedVisualIds=new Set(visuals.map(c=>mediaIdKey(c?.asset)).filter(id=>id!==null));for(const a of assets.filter(x=>usedVisualIds.has(mediaIdKey(x?.id))&&['video','image'].includes(x.type))){if(a.width&&a.height){const shortSide=Math.min(a.width,a.height),longSide=Math.max(a.width,a.height);if(shortSide<720||longSide<1280)warnings.push(`Resolución baja para render profesional: ${a.name} (${a.width}×${a.height})`);const landscape=a.width>a.height,portrait=a.height>a.width,usesCover=visuals.some(c=>mediaIdKey(c?.asset)===mediaIdKey(a?.id)&&(c.fitMode||'cover')==='cover');if(usesCover&&project.format==='9:16'&&landscape&&a.width/a.height>1.5)warnings.push(`Medio horizontal requerirá recorte fuerte en 9:16: ${a.name}`);if(usesCover&&project.format==='16:9'&&portrait&&a.height/a.width>1.5)warnings.push(`Medio vertical requerirá recorte fuerte en 16:9: ${a.name}`)}}
    for(let track=0;track<=6;track++){const cs=(project.clips||[]).filter(c=>trackKey(c?.track)===track).map(c=>({...c,_qaStart:strictNumber(c?.start),_qaDuration:strictNumber(c?.duration)})).filter(c=>c._qaStart!==null&&c._qaDuration!==null&&c._qaDuration>0).sort((a,b)=>a._qaStart-b._qaStart);for(let i=1;i<cs.length;i++)if(cs[i]._qaStart<cs[i-1]._qaStart+cs[i-1]._qaDuration-.01&&![1,2,3,4,5,6].includes(track))warnings.push(`Solapamiento en ${track}: ${cs[i-1].name} / ${cs[i].name}`)}
    const visualSeconds=this.coverage(visuals,timelineDuration),captionSeconds=this.coverage(captions,timelineDuration),safeDuration=Math.max(.001,timelineDuration),score=Math.max(0,100-issues.length*25-warnings.length*7-Math.round(Math.max(0,.75-visualSeconds/safeDuration)*30));return {ok:issues.length===0,score,issues,warnings,metrics:{duration:project.duration,clips:(project.clips||[]).length,assets:assets.length,visualCoverage:+(visualSeconds/safeDuration*100).toFixed(1),captionCoverage:+(captionSeconds/safeDuration*100).toFixed(1),motionTextClips:motion.length,colorGradedClips:colorGraded.length,activeAudioClips:audio.length,disabledTracks}};
  }
  coverage(clips,duration){const number=value=>{const n=typeof value==='number'?value:Number(typeof value==='string'&&value.trim()?value:NaN);return Number.isFinite(n)?n:null},limit=number(duration);if(limit===null||limit<=0)return 0;const ranges=clips.map(c=>{const start=number(c?.start),length=number(c?.duration);return start===null||length===null||length<=0?null:[Math.max(0,start),Math.min(limit,start+length)]}).filter(r=>r&&r[1]>r[0]).sort((a,b)=>a[0]-b[0]);if(!ranges.length)return 0;let total=0,[s,e]=ranges[0];for(const [a,b] of ranges.slice(1)){if(a<=e)e=Math.max(e,b);else{total+=e-s;s=a;e=b}}return total+e-s}
}
if(typeof window!=='undefined')window.ProfitMenteQAEngine=ProfitMenteQAEngine;if(typeof module!=='undefined'&&module.exports)module.exports={ProfitMenteQAEngine};