import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {ProfitMenteProjectImportEngine}=require('./project-import-engine.js');
const engine=new ProfitMenteProjectImportEngine();
const imported=engine.normalize({name:'Importado',duration:12,format:'16:9',mode:'Automático',clips:[{id:'c1',track:0,start:0,duration:3}],libraryId:'existing-project'});
assert.equal(imported.name,'Importado');
assert.equal(imported.duration,12);
assert.equal(imported.format,'16:9');
assert.equal(imported.mode,'Automático');
assert.equal(imported.clips.length,1);
assert.equal('libraryId' in imported,false,'an imported JSON must never inherit or retain a saved-project library id');
const normalized=engine.normalize({name:'  ',duration:45,format:'9:16',mode:'bad',clips:[]});
assert.equal(normalized.name,'Proyecto importado');
assert.equal(normalized.duration,45);
assert.equal(normalized.format,'9:16');
assert.equal(normalized.mode,'Manual');
assert.deepEqual(normalized.clips,[]);
const missingId=engine.normalize({duration:10,format:'9:16',clips:[{track:0,start:0,duration:1}]});
assert.equal(missingId.clips[0].id,'imported-clip-1','legacy clips without ids receive a stable import id');
assert.throws(()=>engine.normalize(null),/inválido/);
assert.throws(()=>engine.normalize({duration:0,format:'9:16',clips:[]}),/Duración/,'zero duration must not silently become a different project');
assert.throws(()=>engine.normalize({duration:10,format:'4:5',clips:[]}),/Formato/,'unsupported 4:5 must be rejected instead of silently becoming 9:16');
assert.throws(()=>engine.normalize({duration:10,format:'bad',clips:[]}),/Formato/,'unknown formats must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:'bad'}),/Timeline/,'a malformed timeline must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:-1,start:0,duration:1}]}),/Pista/,'negative tracks must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:7,start:0,duration:1}]}),/Pista/,'tracks outside Studio must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:0,start:-1,duration:1}]}),/Tiempo/,'negative clip times must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:0,start:0,duration:0}]}),/Tiempo/,'zero-length clips must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:0,start:9.5,duration:1}]}),/duración del proyecto/,'clips extending beyond the project duration must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{track:0,start:10,duration:1}]}),/duración del proyecto/,'clips starting at or beyond the project end must be rejected');
assert.throws(()=>engine.normalize({duration:86400,format:'9:16',clips:[{track:0,start:86399,duration:2}]}),/fuera de rango/,'absurd clip endpoints must be rejected');
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:[{id:'dup',track:0,start:0,duration:1},{id:'dup',track:1,start:1,duration:1}]}),/duplicado/,'duplicate clip ids must be rejected before edit tools can target the wrong clip');
const tooMany=Array.from({length:10001},(_,i)=>({id:`c${i}`,track:0,start:0,duration:1}));
assert.throws(()=>engine.normalize({duration:10,format:'9:16',clips:tooMany}),/demasiado grande/,'huge timelines must be bounded before cloning every clip');
console.log('Safe project import QA passed');
