import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {ProfitMenteMediaStore}=require('./media-store.js');
class Backend{constructor(items=[]){this.items=items.slice();this.failLoad=false;this.failWrite=false;this.failDelete=false}async loadAll(){if(this.failLoad)throw new Error('read denied');return this.items.slice()}async putMany(incoming){if(this.failWrite)throw new Error('quota exceeded');const byId=new Map(this.items.map(x=>[String(x.id),x]));for(const x of incoming)byId.set(String(x.id),x);this.items=[...byId.values()]}async deleteMany(ids){if(this.failDelete)throw new Error('delete denied');const gone=new Set(ids.map(String));this.items=this.items.filter(x=>!gone.has(String(x.id)))}}
class DelayedBackend extends Backend{constructor(items=[]){super(items);this.putCalls=[];this.started=new Promise(resolve=>this.markStarted=resolve);this.gate=new Promise(resolve=>this.releaseFirst=resolve)}async putMany(incoming){this.putCalls.push(incoming.map(x=>({...x})));if(this.putCalls.length===1){this.markStarted();await this.gate}return super.putMany(incoming)}}
const backend=new Backend([{id:'old',name:'Persistido',type:'image'}]),store=new ProfitMenteMediaStore(backend);let loaded=await store.loadAll();assert.equal(loaded.length,1);assert.equal(store.storageAvailable,true);
backend.failWrite=true;await store.put({id:'new',name:'Sesión',type:'video'});assert.equal(store.storageAvailable,false);assert.equal(store.dirty.size,1);loaded=await store.loadAll();assert.equal(loaded.length,2,'a stale persistent read must not replace unsynced session media');assert.equal(loaded.find(x=>x.id==='new').name,'Sesión');
backend.failWrite=false;await store.put({id:'audio',name:'Voz',type:'audio'});assert.equal(store.storageAvailable,true);assert.equal(store.dirty.size,0);assert.deepEqual(new Set(backend.items.map(x=>x.id)),new Set(['old','new','audio']),'recovery flushes media that failed earlier as well as the new asset');
backend.failDelete=true;assert.equal(await store.delete('old'),true);assert.equal(store.get('old'),null,'deleted media disappears from the active session immediately');assert.equal(store.storageAvailable,false);assert.equal(store.pendingDeletes.has('old'),true);assert.equal((await store.loadAll()).some(x=>x.id==='old'),false,'failed persistent delete must not resurrect media in-session');
backend.failDelete=false;await store.flush();assert.equal(store.storageAvailable,true);assert.equal(store.pendingDeletes.size,0);assert.equal(backend.items.some(x=>x.id==='old'),false,'pending media deletion is committed after storage recovery');
const denied=new ProfitMenteMediaStore(null);assert.deepEqual(await denied.loadAll(),[]);await denied.put({id:'session-only',name:'Temporal',type:'image'});assert.equal(denied.storageAvailable,false);assert.equal((await denied.loadAll())[0].id,'session-only');assert.equal(await denied.delete('session-only'),true);assert.deepEqual(await denied.loadAll(),[],'session-only media can still be deleted without IndexedDB');
await assert.rejects(()=>store.put({id:'',name:'bad'}),/id válido/);

// A second update can arrive while IndexedDB is still committing the first one.
// The latest in-memory asset must win and remain dirty until that exact version is persisted.
const raceBackend=new DelayedBackend(),raceStore=new ProfitMenteMediaStore(raceBackend);const firstPut=raceStore.put({id:'same',name:'v1',type:'video'});await raceBackend.started;const secondPut=raceStore.put({id:'same',name:'v2',type:'video'});raceBackend.releaseFirst();await Promise.all([firstPut,secondPut]);assert.equal(raceBackend.items.find(x=>x.id==='same').name,'v2','latest asset revision must survive overlapping writes');assert.ok(raceBackend.putCalls.length>=2,'a changed asset must be flushed again after the older snapshot commits');assert.equal(raceStore.dirty.size,0);assert.equal(raceStore.storageAvailable,true);

// Delete while a put is in flight: the queued delete must run after the old write,
// otherwise a removed file can be resurrected in persistent storage.
const deleteRaceBackend=new DelayedBackend(),deleteRaceStore=new ProfitMenteMediaStore(deleteRaceBackend);const inflightPut=deleteRaceStore.put({id:'gone',name:'Eliminar',type:'image'});await deleteRaceBackend.started;const inflightDelete=deleteRaceStore.delete('gone');deleteRaceBackend.releaseFirst();await Promise.all([inflightPut,inflightDelete]);assert.equal(deleteRaceStore.get('gone'),null);assert.equal(deleteRaceBackend.items.some(x=>x.id==='gone'),false,'delete queued during a write must win in persistent storage');assert.equal(deleteRaceStore.pendingDeletes.size,0);

const index=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.ok(index.indexOf('media-store.js')<index.indexOf('app.js'),'media store must load before app.js');assert.match(app,/new ProfitMenteMediaStore\(\)/);assert.match(app,/mediaStore\.loadAll\(\)/);assert.match(app,/mediaStore\.put\(a\)/);
console.log('Studio resilient media storage + deletion recovery + concurrent flush ordering + runtime wiring OK');
