import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {ProfitMenteProjectImportEngine}=require('./project-import-engine.js');
const engine=new ProfitMenteProjectImportEngine();
const imported=engine.normalize({name:'Importado',duration:12,format:'16:9',mode:'Automático',clips:[{id:'c1',track:0,start:0,duration:3}],libraryId:'existing-project'});
assert.equal(imported.name,'Importado');
assert.equal(imported.duration,12);
assert.equal(imported.format,'16:9');
assert.equal(imported.mode,'Automático');
assert.equal(imported.clips.length,1);
assert.equal('libraryId' in imported,false,'an imported JSON must never inherit or retain a saved-project library id');
const normalized=engine.normalize({name:'  ',duration:0,format:'bad',mode:'bad',clips:'bad'});
assert.equal(normalized.name,'Proyecto importado');
assert.equal(normalized.duration,45);
assert.equal(normalized.format,'9:16');
assert.equal(normalized.mode,'Manual');
assert.deepEqual(normalized.clips,[]);
assert.throws(()=>engine.normalize(null),/inválido/);
console.log('Safe project import QA passed');
