import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const Engine=require('./visual-crop-engine.js');
const e=new Engine();
assert.deepEqual(e.state({}),{left:0,right:0,top:0,bottom:0});
assert.deepEqual(e.normalize({left:-5,right:120,top:'10',bottom:'bad'}),{left:0,right:95,top:10,bottom:0});
const pair=e.normalize({left:80,right:80,top:70,bottom:70});
assert.ok(Math.abs(pair.left+pair.right-95)<1e-9);
assert.ok(Math.abs(pair.top+pair.bottom-95)<1e-9);
const project={trackState:{'1':{locked:false}}},clip={id:1,track:1,type:'video'};
let r=e.apply(project,clip,{left:10,right:5,top:2,bottom:3});
assert.equal(r.ok,true);assert.equal(r.changed,true);assert.deepEqual(clip.visualCrop,{left:10,right:5,top:2,bottom:3});
const rect=e.sourceRect({videoWidth:1920,videoHeight:1080},clip);
assert.deepEqual(rect,{x:192,y:21.6,w:1632,h:1026});
project.trackState['1'].locked=true;const before=JSON.stringify(clip.visualCrop);r=e.apply(project,clip,{left:20});assert.equal(r.reason,'locked');assert.equal(JSON.stringify(clip.visualCrop),before);
project.trackState['1'].locked=false;r=e.reset(project,clip);assert.equal(r.ok,true);assert.equal(r.changed,true);assert.equal('visualCrop' in clip,false);
assert.equal(e.apply(project,{track:3,type:'caption'},{left:10}).reason,'ineligible');
console.log('visual crop regression: ok');
