import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

globalThis.window=globalThis;
vm.runInThisContext(fs.readFileSync(new URL('./media-import-engine.js',import.meta.url),'utf8'),{filename:'media-import-engine.js'});
const E=globalThis.ProfitMenteMediaImportEngine;
assert.ok(E,'media import engine must be exported');
assert.equal(E.kind({name:'clip.MP4',type:''}),'video');
assert.equal(E.kind({name:'voice.bin',type:'audio/ogg'}),'audio');
assert.equal(E.kind({name:'cover.webp',type:''}),'image');
assert.equal(E.kind({name:'notes.txt',type:'text/plain'}),null);
const file={name:'Take 01.mp4',type:'video/mp4',size:12345,lastModified:42};
const signature=E.signature(file);
assert.equal(signature,'take 01.mp4|12345|video/mp4|42');
assert.equal(E.compatible([file,{name:'readme.txt',type:'text/plain'}]).length,1);
assert.equal(E.findDuplicate([{id:'a',name:'Take 01.mp4',mime:'video/mp4',blob:{size:12345},sourceLastModified:42}],file)?.id,'a');
assert.equal(E.findDuplicate([{id:'b',sourceFingerprint:signature}],file)?.id,'b');
assert.equal(E.findDuplicate([{id:'c',name:'Take 02.mp4',mime:'video/mp4',blob:{size:12345},sourceLastModified:42}],file),null);

const original=new Blob([new TextEncoder().encode('profitmente-media-content')],{type:'video/mp4'});
Object.defineProperty(original,'name',{value:'original.mp4'});Object.defineProperty(original,'lastModified',{value:1});
const renamed=new Blob([new TextEncoder().encode('profitmente-media-content')],{type:'video/mp4'});
Object.defineProperty(renamed,'name',{value:'renamed-copy.mp4'});Object.defineProperty(renamed,'lastModified',{value:999});
const different=new Blob([new TextEncoder().encode('profitmente-media-different')],{type:'video/mp4'});
Object.defineProperty(different,'name',{value:'different.mp4'});
const hashA=await E.contentHash(original),hashB=await E.contentHash(renamed),hashC=await E.contentHash(different);
assert.ok(hashA&&hashA.length===64,'content hash must be SHA-256 hex');
assert.equal(hashA,hashB,'renamed copies with identical bytes must share a content hash');
assert.notEqual(hashA,hashC,'different media bytes must not collide in regression fixture');
assert.equal(E.findDuplicateHash([{id:'same',sourceContentHash:hashA}],hashB)?.id,'same');
assert.equal(E.findDuplicateHash([{id:'other',sourceContentHash:hashC}],hashB),null);
console.log('media import engine regression passed');
