import assert from 'node:assert/strict';
import mod from './project-export-engine.js';
const {ProfitMenteProjectExportEngine}=mod;
const engine=new ProfitMenteProjectExportEngine();
const project={libraryId:'local-1',name:'Prueba',duration:12,format:'9:16',clips:[{id:'a',track:0,start:0,duration:5,asset:7},{id:'b',track:0,start:5,duration:5,asset:'missing'},{id:'c',track:3,start:0,duration:2,asset:null}],assets:[{id:7,name:'viejo.mp4',duration:4,sourceContentHash:'oldhash'},{id:'missing',name:'missing.mp4',duration:9,sourceFingerprint:'fp-missing'},{id:'unused-old',name:'unused.mp4'}]};
const live=[{id:'7',name:'nuevo.mp4',type:'video',mime:'video/mp4',size:1234,duration:8.25,width:1920,height:1080,metadataVersion:2,sourceContentHash:'newhash',sourceFingerprint:'fp-7',blob:{secret:true},url:'blob:x',previewBlob:{secret:true}},{id:'unused',name:'no.json',type:'video',duration:99}];
const before=structuredClone(project);
const envelope=engine.build(project,live,'2026-09-11T12:00:00.000Z');
assert.equal(envelope.kind,'profitmente-studio-project');
assert.equal(envelope.schemaVersion,2);
assert.equal(envelope.project.libraryId,undefined);
assert.deepEqual(project,before,'export must not mutate the active project');
assert.equal(envelope.project.assets.length,2,'only media referenced by clips should be exported');
const seven=envelope.project.assets.find(a=>engine.idKey(a.id)==='n:7');
assert.ok(seven);
assert.equal(seven.name,'nuevo.mp4');
assert.equal(seven.duration,8.25);
assert.equal(seven.width,1920);
assert.equal(seven.sourceContentHash,'newhash');
assert.equal('blob' in seven,false);
assert.equal('url' in seven,false);
assert.equal('previewBlob' in seven,false);
const missing=envelope.project.assets.find(a=>a.id==='missing');
assert.equal(missing.name,'missing.mp4','metadata from an offline asset must survive export');
assert.equal(missing.duration,9);
assert.equal(missing.sourceFingerprint,'fp-missing');
assert.equal(envelope.project.assets.some(a=>a.id==='unused'),false);
assert.equal(envelope.project.assets.some(a=>a.id==='unused-old'),false);
const parsed=JSON.parse(engine.serialize(project,live,'2026-09-11T12:00:00.000Z'));
assert.equal(parsed.project.assets[0].size,1234);
assert.throws(()=>engine.build({...project,clips:[{id:'x',track:0,start:0,duration:1,asset:7}]},[{id:7},{id:'7'}]),/duplicado|ambiguo/,'ambiguous live identities must block export');
assert.equal(engine.safeFileName(' Mi vídeo / prueba '),'Mi-video-prueba');
console.log('Project export media metadata regression: ok');
