const assert=require('assert');
require('./startup-project-guard.js');
const guard=globalThis.ProfitMenteStartupProjectGuard;
assert.ok(guard,'startup project guard must load');
assert.strictEqual(guard.MAX_PROJECT_CLIPS,10000);
const base={name:'Saved',mode:'Manual',duration:45,format:'9:16',clips:[]};
assert.ok(guard.normalizeProject(base));
assert.strictEqual(guard.normalizeProject({...base,clips:[null]}),null,'null clips must not reach the editor');
assert.strictEqual(guard.normalizeProject({...base,clips:['bad']}),null,'scalar clips must not reach the editor');
assert.strictEqual(guard.normalizeProject({...base,clips:[[]]}),null,'array clips must not reach the editor');
assert.ok(guard.normalizeProject({...base,clips:[{}]}),'object clips remain compatible with legacy projects');
const oversized=Array.from({length:guard.MAX_PROJECT_CLIPS+1},()=>({}));
assert.strictEqual(guard.normalizeProject({...base,clips:oversized}),null,'startup recovery must reject timelines beyond the import/render project budget');
const store=new Map();
store.set(guard.PRIMARY_KEY,JSON.stringify({...base,clips:[null]}));
const storage={getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,value),removeItem:key=>store.delete(key)};
const result=guard.guard(storage);
assert.strictEqual(result.quarantined,true,'malformed startup projects must be quarantined');
assert.ok(store.has(guard.BACKUP_KEY),'malformed startup projects must be preserved for recovery');
assert.strictEqual(store.has(guard.PRIMARY_KEY),false,'malformed primary project must not remain active');
console.log('startup project structure: ok');
