import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve('studio');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script\s+src="([^"]+)"/g)].map(m=>m[1]);
const missing=scripts.filter(s=>!fs.existsSync(path.join(root,s)));
if(missing.length) throw new Error('Scripts faltantes: '+missing.join(', '));
const dup=scripts.filter((s,i)=>scripts.indexOf(s)!==i);
if(dup.length) throw new Error('Scripts duplicados en index.html: '+[...new Set(dup)].join(', '));
const requiredControls=['autoBtn','manualBtn','playBtn','qaBtn','exportBtn','bundleBtn','renderMp4Btn','renderBtn','uploadBtn','importBtn','importBundleBtn','saveBtn'];
for(const id of requiredControls) if(!html.includes(`id="${id}"`)) throw new Error(`Control requerido ausente: ${id}`);
for(const script of ['preview-engine.js','project-library.js','relink-engine.js','bundle-engine.js','qa-engine.js']) if(!scripts.includes(script)) throw new Error(`Módulo crítico no conectado: ${script}`);
const inspector=fs.readFileSync(path.join(root,'clip-inspector.js'),'utf8');
if(inspector.includes("projectLibraryScript")||inspector.includes("project-library.js';document.body.appendChild")) throw new Error('clip-inspector.js vuelve a cargar project-library.js');
for(const token of ['hook-pop','dynamic','word-pulse','cut','fade','slide','zoom']) if(!inspector.includes(token)) throw new Error('Inspector no expone opción compatible con renderer: '+token);
const relink=fs.readFileSync(path.join(root,'relink-engine.js'),'utf8');
for(const token of ['Reconectar medios','missing(project,assets','match(project,assets,files)']) if(!relink.includes(token)) throw new Error('Relink incompleto: '+token);
const library=fs.readFileSync(path.join(root,'project-library.js'),'utf8');
if(/createElement\(['"]script['"]\)[\s\S]*relink-engine\.js/.test(library)||library.includes("relink.src='relink-engine.js'")) throw new Error('project-library.js vuelve a cargar relink-engine.js dinámicamente');
const generator=fs.readFileSync(path.join(root,'generator-integration.js'),'utf8');
for(const token of ["window.addEventListener('load',bootRecovery",'recovery-engine.js','recovery-integration.js']) if(!generator.includes(token)) throw new Error('Recuperación no tiene carga determinista: '+token);
console.log(`Studio integrity OK: ${scripts.length} scripts, ${requiredControls.length} controles críticos`);
