import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {ProfitMenteTimelineLeftTrimEngine:E}=require('./timeline-left-trim.js');
const {ProfitMenteTimelineSnapEngine:S}=require('./timeline-snap-engine.js');
const project={duration:20,clips:[{id:'a',track:0,start:5,duration:6,asset:'v1'},{id:'b',track:0,start:2,duration:2}]};
let clip={...project.clips[0],sourceOffset:3,speed:2};
let r=E.calculate(project,clip,6,{sourceBound:true,snapEngine:null});
assert.equal(r.start,6);assert.equal(r.duration,5);assert.equal(r.sourceOffset,5,'trimming one timeline second at 2x must advance source by two seconds');
r=E.calculate(project,clip,3.5,{sourceBound:true,snapEngine:null});
assert.equal(r.start,3.5);assert.equal(r.duration,7.5);assert.equal(r.sourceOffset,0,'left extension must consume available source offset without going negative');
r=E.calculate(project,clip,2,{sourceBound:true,snapEngine:null});
assert.equal(r.start,3.5,'source-bound clip must not extend before available source media');assert.equal(r.sourceOffset,0);
r=E.calculate(project,{...clip,sourceOffset:0},4.04,{sourceBound:false,snapEngine:S,tolerance:.1});
assert.equal(r.snapped,true);assert.equal(r.start,4);assert.equal(r.duration,7);assert.equal(r.target,4,'left trim should snap to another clip boundary');
r=E.calculate(project,{...clip,sourceOffset:0},4.04,{sourceBound:false,snapEngine:null,tolerance:.1});
assert.equal(r.snapped,false);assert.equal(r.start,4.04,'disabling snap should preserve free trim position');
r=E.calculate({duration:20,clips:[{id:7,start:5,duration:6},{id:'other',start:12,duration:2}]},{id:'007',start:5,duration:6},5.04,{snapEngine:S,tolerance:.1});
assert.equal(r.snapped,false,'canonical ID alias must exclude the clip from its own snap points');
r=E.calculate(project,{id:'x',start:10,duration:1},10.9,{minDuration:.25});
assert.equal(r.start,10.75);assert.equal(r.duration,.25,'left trim must preserve minimum duration');
const bootstrap=fs.readFileSync(new URL('./feature-bootstrap.js',import.meta.url),'utf8');
assert.match(bootstrap,/timeline-left-trim\.js/,'left trim must load from the shared feature bootstrap');
const integration=fs.readFileSync(new URL('./timeline-left-trim.js',import.meta.url),'utf8');
assert.match(integration,/e\.stopImmediatePropagation\(\)/,'left edge owner must prevent the legacy move drag from starting');
assert.match(integration,/e\.altKey\?null:Snap/,'Alt must bypass magnetic snapping while left trimming');
console.log('timeline left trim regression: ok');
