const assert=require('assert');
require('./startup-project-guard.js');
const guard=globalThis.ProfitMenteStartupProjectGuard;
assert.ok(guard,'startup project guard must load');
assert.strictEqual(guard.MAX_RENDER_DURATION,21600);
const legacy=guard.normalizeProject({name:'Legacy',mode:'Manual',duration:45,format:'9:16',clips:[]});
assert.strictEqual(legacy.fps,30);
assert.strictEqual(legacy.renderQuality,'high');
const oversized=guard.normalizeProject({name:'Long',mode:'Manual',duration:86400,format:'16:9',fps:60,renderQuality:'standard',clips:[]});
assert.strictEqual(oversized.duration,21600,'startup recovery must not restore a project beyond the local render budget');
assert.strictEqual(oversized.fps,60);
assert.strictEqual(oversized.renderQuality,'standard');
const badQuality=guard.normalizeProject({name:'Q',mode:'Manual',duration:30,format:'1:1',fps:24,renderQuality:'ultra',clips:[]});
assert.strictEqual(badQuality.renderQuality,'high','unsupported saved render quality must recover to the local renderer default');
const normalized=guard.serializeProject({name:'Saved',mode:'Automático',duration:99999,format:'9:16',fps:120,renderQuality:' ULTRA ',clips:[]}).project;
assert.strictEqual(normalized.duration,21600);
assert.strictEqual(normalized.fps,30);
assert.strictEqual(normalized.renderQuality,'high');
console.log('startup render limits: ok');
