import assert from 'node:assert/strict';
import './roll-edit-engine.js';
const engine=new globalThis.ProfitMenteRollEditEngine();
const leftAsset={id:'a',type:'video',duration:20};
const rightAsset={id:'b',type:'video',duration:20};
let left={id:'l',track:0,asset:'a',start:0,duration:5,sourceOffset:2,speed:1};
let right={id:'r',track:0,asset:'b',start:5,duration:4,sourceOffset:3,speed:1};
let r=engine.roll(left,right,leftAsset,rightAsset,.5);
assert.equal(r.ok,true);assert.equal(r.changed,true);assert.equal(r.preservedTotal,true);
assert.equal(left.duration,5.5);assert.equal(right.start,5.5);assert.equal(right.duration,3.5);assert.equal(right.sourceOffset,3.5);assert.equal(left.duration+right.duration,9);
r=engine.roll(left,right,leftAsset,rightAsset,-1);
assert.equal(left.duration,4.5);assert.equal(right.start,4.5);assert.equal(right.duration,4.5);assert.equal(right.sourceOffset,2.5);assert.equal(left.duration+right.duration,9);
const fastLeft={id:'fl',track:0,asset:'a',start:0,duration:2,sourceOffset:15,speed:2};
const fastRight={id:'fr',track:0,asset:'b',start:2,duration:3,sourceOffset:1,speed:2};
r=engine.roll(fastLeft,fastRight,leftAsset,rightAsset,10);
assert.equal(r.clamped,true);assert.equal(r.delta,.5,'left extension must stop when source reaches asset end');assert.equal(fastLeft.duration,2.5);assert.equal(fastRight.sourceOffset,2,'right source offset must advance in source time at playback speed');
const backLeft={id:'bl',track:0,asset:'a',start:0,duration:4,sourceOffset:0,speed:1};
const backRight={id:'br',track:0,asset:'b',start:4,duration:2,sourceOffset:.2,speed:2};
r=engine.roll(backLeft,backRight,leftAsset,rightAsset,-2);
assert.equal(r.clamped,true);assert.equal(r.delta,-.1,'moving boundary left must not require source before zero on right clip');assert.equal(backRight.sourceOffset,0);
const tinyLeft={id:'tl',track:0,asset:'a',start:0,duration:.1,sourceOffset:0,speed:1};
const tinyRight={id:'tr',track:0,asset:'b',start:.1,duration:.1,sourceOffset:0,speed:1};
r=engine.roll(tinyLeft,tinyRight,leftAsset,rightAsset,1);assert.equal(r.delta,.05);assert.equal(tinyRight.duration,.05,'roll must preserve minimum right clip duration');
const gapLeft={id:'g1',track:0,start:0,duration:2};const gapRight={id:'g2',track:0,start:2.2,duration:2};r=engine.roll(gapLeft,gapRight,null,null,.1);assert.equal(r.ok,false);assert.equal(r.reason,'not-adjacent');
const pair=engine.findPair([{id:'x',track:0,start:0,duration:2},{id:'y',track:0,start:2,duration:3}], 'x');assert.equal(pair.left.id,'x');assert.equal(pair.right.id,'y');assert.equal(pair.selectedSide,'left');
const pairFromRight=engine.findPair([{id:'x',track:0,start:0,duration:2},{id:'y',track:0,start:2,duration:3}], 'y');assert.equal(pairFromRight.left.id,'x');assert.equal(pairFromRight.right.id,'y');assert.equal(pairFromRight.selectedSide,'right');
console.log('ProfitMente roll edit QA passed');
