import {createRequire} from 'module';
const require=createRequire(import.meta.url);
const {ProfitMenteAudioEnvelopeEngine}=require('./audio-envelope-engine.js');
const e=new ProfitMenteAudioEnvelopeEngine();
let x=e.normalize(10,2,3);if(Math.abs(x.fadeIn-2)>.001||Math.abs(x.fadeOut-3)>.001)throw new Error('normal fade failed');
x=e.normalize(1,1,1);if(Math.abs(x.fadeIn-.5)>.001||Math.abs(x.fadeOut-.5)>.001)throw new Error('overlap normalization failed');
const c={duration:4,fadeIn:1,fadeOut:1};
const near=(a,b)=>Math.abs(a-b)<.02;
if(!near(e.gainAt(c,0),0)||!near(e.gainAt(c,.5),.5)||!near(e.gainAt(c,2),1)||!near(e.gainAt(c,3.5),.5)||!near(e.gainAt(c,4),0))throw new Error('gain curve failed');
console.log('Audio envelope engine OK');