import assert from 'node:assert/strict';import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {ProfitMenteMediaStore}=require('./media-store.js');
class Backend{constructor(items=[]){this.items=items.slice();this.failLoad=false;this.failWrite=false}async loadAll(){if(this.failLoad)throw new Error('read denied');return this.items.slice()}async putMany(incoming){if(this.failWrite)throw new Error('quota exceeded');const byId=new Map(this.items.map(x=>[String(x.id),x]));for(const x of incoming)byId.set(String(x.id),x);this.items=[...byId.values()]}}
const backend=new Backend([{id:'old',name:'Persistido',type:'image'}]),store=new ProfitMenteMediaStore(backend);let loaded=await store.loadAll();assert.equal(loaded.length,1);assert.equal(store.storageAvailable,true);
backend.failWrite=true;await store.put({id:'new',name:'Sesión',type:'video'});assert.equal(store.storageAvailable,false);assert.equal(store.dirty.size,1);loaded=await store.loadAll();assert.equal(loaded.length,2,'a stale persistent read must not replace unsynced session media');assert.equal(loaded.find(x=>x.id==='new').name,'Sesión');
backend.failWrite=false;await store.put({id:'audio',name:'Voz',type:'audio'});assert.equal(store.storageAvailable,true);assert.equal(store.dirty.size,0);assert.deepEqual(new Set(backend.items.map(x=>x.id)),new Set(['old','new','audio']),'recovery flushes media that failed earlier as well as the new asset');
const denied=new ProfitMenteMediaStore(null);assert.deepEqual(await denied.loadAll(),[]);await denied.put({id:'session-only',name:'Temporal',type:'image'});assert.equal(denied.storageAvailable,false);assert.equal((await denied.loadAll())[0].id,'session-only');
await assert.rejects(()=>store.put({id:'',name:'bad'}),/id válido/);
const index=fs.readFileSync(new URL('./index.html',import.meta.url),'utf8'),app=fs.readFileSync(new URL('./app.js',import.meta.url),'utf8');assert.ok(index.indexOf('media-store.js')<index.indexOf('app.js'),'media store must load before app.js');assert.match(app,/new ProfitMenteMediaStore\(\)/);assert.match(app,/mediaStore\.loadAll\(\)/);assert.match(app,/mediaStore\.put\(a\)/);
console.log('Studio resilient media storage + runtime wiring OK');
