import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const root=path.dirname(fileURLToPath(import.meta.url));
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const scripts=[...html.matchAll(/<script\s+src="([^"]+)"/g)].map(m=>m[1]);
const missing=scripts.filter(s=>!fs.existsSync(path.join(root,s)));
if(missing.length) throw new Error('Scripts faltantes: '+missing.join(', '));
const dup=scripts.filter((s,i)=>scripts.indexOf(s)!==i);
if(dup.length) throw new Error('Scripts duplicados en index.html: '+[...new Set(dup)].join(', '));
const requiredControls=['autoBtn','manualBtn','playBtn','qaBtn','exportBtn','bundleBtn','renderMp4Btn','renderBtn','uploadBtn','importBtn','importBundleBtn','saveBtn'];
for(const id of requiredControls) if(!html.includes(`id="${id}"`)) throw new Error(`Control requerido ausente: ${id}`);
for(const script of ['preview-engine.js','project-library.js','relink-engine.js','bundle-engine.js','qa-engine.js']) if(!scripts.includes(script)) throw new Error(`Módulo crítico no conectado: ${script}`);
const inspector=fs.readFileSync(path.join(root,'clip-inspector.js'),'utf8');
if(inspector.includes("projectLibraryScript")||inspector.includes("project-library.js';document.body.appendChild")) throw new Error('clip-inspector.js vuelve a cargar project-library.js');
for(const token of ['hook-pop','dynamic','word-pulse','cut','fade','slide','zoom']) if(!inspector.includes(token)) throw new Error('Inspector no expone opción compatible con renderer: '+token);
const relink=fs.readFileSync(path.join(root,'relink-engine.js'),'utf8');
for(const token of ['Reconectar medios','missing(project,assets','match(project,assets,files)']) if(!relink.includes(token)) throw new Error('Relink incompleto: '+token);
const library=fs.readFileSync(path.join(root,'project-library.js'),'utf8');
if(/createElement\(['"]script['"]\)[\s\S]*relink-engine\.js/.test(library)||library.includes("relink.src='relink-engine.js'")) throw new Error('project-library.js vuelve a cargar relink-engine.js dinámicamente');
const generator=fs.readFileSync(path.join(root,'generator-integration.js'),'utf8');
for(const token of ["window.addEventListener('load',bootSupportModules",'project-portability.js','bootRecovery','recovery-engine.js','recovery-integration.js']) if(!generator.includes(token)) throw new Error('Carga de soporte/recuperación no tiene integración determinista: '+token);
const portability=fs.readFileSync(path.join(root,'project-portability.js'),'utf8');
for(const token of ['ProfitMenteProjectPortability','metadataVersion','duration','width','height','projectInput','exportBtn']) if(!portability.includes(token)) throw new Error('Portabilidad de proyecto incompleta: '+token);
const mediaInspector=fs.readFileSync(path.join(root,'media-inspector.js'),'utf8');
for(const token of ['media-library-tools.js','profitmenteMediaLibraryTools']) if(!mediaInspector.includes(token)) throw new Error('Herramientas de biblioteca de medios no conectadas: '+token);
const trackControls=fs.readFileSync(path.join(root,'track-controls.js'),'utf8');
if(trackControls.includes('project.clips=all.filter')||trackControls.includes('project.clips=all')) throw new Error('Track controls vuelve a reemplazar project.clips durante el preview asíncrono');
for(const token of ['isVisualHidden','isAudioMuted']) if(!trackControls.includes(token)) throw new Error('Track controls no expone estado seguro de pista: '+token);
const preview=fs.readFileSync(path.join(root,'preview-engine.js'),'utf8');
for(const token of ['trackHidden(Number(c.track))','if(trackHidden(3))return','isTrackHidden:trackHidden']) if(!preview.includes(token)) throw new Error('Preview no respeta pistas ocultas directamente: '+token);
const captionPreview=fs.readFileSync(path.join(root,'caption-preview.js'),'utf8');
for(const token of ['captionsHidden()','ProfitMenteCaptionPreview']) if(!captionPreview.includes(token)) throw new Error('Preview de captions no respeta pista oculta: '+token);
const MediaLibraryTools=require(path.join(root,'media-library-tools.js'));
const sample=[{id:'v1',name:'Mercado Ágil.mp4',type:'video',mime:'video/mp4'},{id:'a1',name:'voz.wav',type:'audio',mime:'audio/wav'}];
if(MediaLibraryTools.filter(sample,'mercado','video').map(x=>x.id).join(',')!=='v1') throw new Error('Filtro de biblioteca no encuentra medios por nombre/tipo');
if(MediaLibraryTools.filter(sample,'voz','video').length!==0) throw new Error('Filtro de biblioteca ignora el tipo seleccionado');
const project={clips:[{id:'c1',asset:'v1'}]};if(MediaLibraryTools.usage(project,'v1').length!==1) throw new Error('Biblioteca no detecta uso de medios');
MediaLibraryTools.preserveMeta(project,{id:'v1',name:'Mercado Ágil.mp4',type:'video',duration:4.5,width:1920,height:1080,size:1234,blob:{}});
if(project.assets?.[0]?.width!==1920||project.assets?.[0]?.duration!==4.5||'blob' in project.assets[0]) throw new Error('Biblioteca no conserva metadata portable antes de borrar un medio usado');
console.log(`Studio integrity OK: ${scripts.length} scripts, ${requiredControls.length} controles críticos, biblioteca de medios administrable y preview de pistas seguro`);
